---
title: "Biodiversity development"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r initialize}
source("/Users/christophercrawford/work/projects/biodiversity_abn/scripts/0_start.R")
# install.packages("terra")
# packageVersion("terra")
# library(terra)

# load files:
source("/Users/christophercrawford/work/projects/biodiversity_abn/scripts/util/_util_files.R")
```



# Area raster:

```{r calculate-area-ha}
ifelse(
  !dir.exists(paste0(p_derived, "site_area_ha")), 
  dir.create(paste0(p_derived, "site_area_ha")), 
  FALSE)


site_area_ha <- lapply(1:11, function(i) {
  terra::cellSize(age_t[[i]]$y2017, unit = "ha", mask = FALSE,
                  overwrite = TRUE,
                  names = paste0(site_df$site[i], "_area_ha"),
                  filename = paste0(p_derived, "site_area_ha/", site_df$site[i], "_area_ha.tif"))
  }
)


site_area_ha <- lapply(
  list.files(paste0(p_derived, "site_area_ha"), full.names = TRUE), 
  function(i) rast(i)
  )
names(site_area_ha) <- site_df$site
```




# Scenarios

## Variation in forest restoration success

```{r var-forest-restoration-success}
var_forest_success_files <- list.files(paste0(p_ee, "var_for_success"), full.names = TRUE)

var_restoration_native <- lapply(
  grep("native", var_forest_success_files, value = TRUE), 
  function(i) {terra::rast(i)})
names(var_restoration_native) <- site_df$site

plot(var_restoration_native[[9]])

res(var_restoration_native[[9]]) * 110000


# the full file:
my_vers1 <- rast(
  "/Users/christophercrawford/Downloads/var_for_success_full-0000000000-0000032768.tif")
my_vers2 <- rast(
  "/Users/christophercrawford/Downloads/var_for_success_full-0000000000-0000000000.tif")
plot(my_vers1)
plot(my_vers2)

my_vers1
my_vers2

merged <- merge(my_vers1, my_vers2)

plot(merged)
```

```{r save-variation-forest-success}
pdf(file = paste0(p_output, "plots/variation_forest_restoration_success.pdf"), width = 10, height = 7.5)
mval <- 1.5
par(mfrow = c(3, 4), 
      # mar=c(0,0,0,0), 
      oma=c(1,1,0,0), 
      adj = 0,
      cex.main = 1#,
      # tcl = -0.2
      )
    
for(i in 1:11) {
  plot(var_restoration_native[[i]], 
       main = names(var_restoration_native[i]),
       mar = c(mval+0.5, mval, mval + 1.2, mval + 2) # bltr   
       # type = "classes", #legend = FALSE,
       )
  }

dev.off()
```

```{r bd-restoration-success}
prieto_files <- list.files(paste0(p_dat, "Bd/Prieto_2021_cons_bio"), 
           full.names = TRUE) %>% 
  grep(".tif", ., value = TRUE)

var_vert_richness <- rast(prieto_files[6])

# ext(var_vert_richness) <- ext(forest_c)
ext(var_vert_richness)
plot(var_vert_richness)
plot(site_sf$geometry, add = T)

# doesn't overlap with enough of my sites to make it worth while
for(i in 1:11) {
  plot(var_vert_richness,
       ext = ext(lc[[i]]),
       maxcell = 1000000000)
  
}



plot(var_vert_richness,
     ext = ext(lc[[8]]),
     maxcell = 1e10)

ext(var_vert_richness)


## crop & resample
site_var_vert_richness <- lapply(1:11, function(i) {
  terra::crop(var_vert_richness, ext(lc[[i]]) + rep(0.1, 4), # with a bit of buffer
              filename = paste0(p_derived, "site_var_bd_rest/", 
                                names(lc[i]), "_var_bd_rest_buff.tif"),
              overwrite = TRUE
              )
  }
  )
names(site_var_vert_richness) <- site_df$site

# load back in
site_var_vert_richness <- lapply(
  list.files(paste0(p_derived, "site_var_bd_rest"), full.names = TRUE) %>%
    grep("var_bd_rest_buff.tif", ., value = TRUE), 
  function(i) rast(i)
  )
names(site_var_vert_richness) <- site_df$site



# ------------------------------------------------------ #
# resample
# ------------------------------------------------------ #
site_var_vert_richness_30 <- lapply(1:11, function(i) {
  terra::resample(
    x = site_jung_l1[[i]], y = lc[[i]]$y2017, method = "near",
    filename = paste0(p_derived, "site_var_bd_rest/", names(lc[i]), "_var_bd_rest_30.tif"),
    names = paste0(names(lc[i]), "_var_bd_rest_30"),
    overwrite = TRUE)
  }
  )

# load back in
site_var_vert_richness_30 <- lapply(
  list.files(paste0(p_derived, "site_var_bd_rest"), full.names = TRUE) %>% grep("_var_bd_rest_30.tif", ., value = TRUE), 
  function(i) rast(i)
  )
names(site_var_vert_richness_30) <- site_df$site

```

# Other

```{r abn-lc-forest}

# Mask land cover map for the year 2017 by the abandonment age map, returning the land cover class for all abandonment of 5 years of more.

abn_lc_t <- lapply(11, function(i) {
  terra::mask(x = lc[[i]]$y2017, 
              mask = age_t[[i]]$y2017,
              # exclude NA values, and age values of 0 through 4
              maskvalues = c(NA, 0:4),
              
              filename = paste0(p_derived, "abn_lc_rasters/", site_df$site[i], "_abn_lc.tif"),
              overwrite = TRUE
              )
})
names(abn_lc_t) <- site_df$site


abn_lc_t <- lapply(
  list.files(paste0(p_derived, "abn_lc_rasters"), full.names = TRUE),
  function(i) {rast(i)}
  )
names(abn_lc_t) <- site_df$site


i <- 11
plot(abn_lc_t[[i]], col = "black")
plot(age_t[[i]]$y2017, col = "black", breaks = c(5, 31))



  

plot(lc_abn_mask, col = lc_plot_cols$color[2:4])
plot(lc_abn_mask2)#, col = lc_plot_cols$color[c(2,4)])
plot(lc_abn_mask3)#, col = lc_plot_cols$color[c(2,4)])
plot(lc_abn_mask3, col = c("dark green", "light green"))
plot(site_ecoregions2017$geometry, add = T)

show_col(lc_plot_cols$color[c(2,4)])
plot(lc_abn_mask2 - lc_abn_mask3)

age_t[[9]]$y2017 %>% plot(colNA = "gray80")

                  # 


```

# End

```{r clean-up}
env_size(ls())

# 
os <- get_sizes(ls())

os %>% 
  summarise(total_env_size = sum(size)) %>% 
  mutate(gb = total_env_size / 1024^3)

os %>% print(n = 20)


rm(list = os$object[c(1:2)])


tmpFiles(current=TRUE, orphan=FALSE, old=FALSE, 
         remove=TRUE)

```

